version: '2.4'
services:
  pss_proxy:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    links:
      - pss_base
    depends_on:
      - pss_base
    volumes:
      - ./public:/app/public
      - ./docker/nginx/logs:/var/log/nginx

  pss_base:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    env_file:
      - .env
    environment:
        DB_HOST: pss_db
        DB_DATABASE: pss
        DB_USERNAME: pss
        DB_PASSWORD: pss
    depends_on:
      - pss_db
    links:
      - pss_db
    volumes:
      - .:/app
      - ./docker/php-fpm/logs:/var/log/php-fpm

  pss_db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pss
      - MYSQL_USER=pss
      - MYSQL_PASSWORD=pss

  pss_cron:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
        DB_HOST: pss_db
        DB_DATABASE: pss
        DB_USERNAME: pss
        DB_PASSWORD: pss
    mem_limit: 2G
    cpus: '1'
    command: php artisan schedule:run
    volumes:
      - .:/app
